#!/usr/bin/env bash
main() {
  chapter=$1
  exercise=$2
  shift
  shift
  compile_ex $1 $2 && run $@
}

compile_ex() {
  file_path="exercises/chapter$chapter/exercise$exercise.c"
  compile $file_path
}

run() {
  ./a.out $@
}

main $@;