#!/usr/bin/env bash
run_tests() {
  echo "=== Running tests ..."
  find_tests | while read in; do run_test $in; done
}

find_tests() {
  find $PROJECT_ROOT \
    | grep -e  "\.test\.sh\$" \
    | sort
}

run_test() {
  cmd="bash $1"
  echo "=== $1"
  eval $cmd || exit $?
  echo "=== 💯"
  echo
}

run_tests